# Generated by Django 5.2.1 on 2025-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cita_veterinario_historia_cita_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tiempo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
